# Generated by Django 5.2.7 on 2025-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cours', models.CharField(default='python', max_length=50)),
                ('data_created_at', models.DateTimeField(auto_now_add=True)),
                ('active_now', models.BooleanField(default=True)),
            ],
        ),
    ]
